### PR TITLE
Change application to library in push rdxml

### PR DESCRIPTION
**Pull request by achocron**
Things to consider before you submit the PR:

It's really dangerous to use the "application" tag in a library's rd xml, since an application my try to use the same tag and there can only be one. Libraries should use the "library" tag, since there can be several of those.

### CODE REVIEW

**Comment by guperrot** [comment]
What is this about?

**Comment by achocron** [comment]
@guperrot Found it while doing the UWP spike. Basically it fixes a warning that you see when you try to compile with an rd.xml file for the application - this warning is bad because it means that only one rd.xml will be actually used. To allow other rd.xml files to coexist, we must use the "library" tag

**Comment by guperrot** [comment]
Is it shipped? Do we need changelog?

**Comment by achocron** [comment]
I believe there is no customer impact since we don't ship it. Can impact apps that reference the project though (so just puppet apps).

**Pull request merged**
