### PR TITLE
Remove AppCenter.SetCustomProperties API

### PR DESCRIPTION
**Pull request by AnastasiaKubova**
Things to consider before you submit the PR:

* [x] Has `CHANGELOG.md` been updated?
* [x] Are tests passing locally?
* [x] Are the files formatted correctly?
* [ ] ~Did you add unit tests if this modifies the Windows code?~
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?

## Description

1) Remove AppCenter.setCustomProperties API from: 
  - SDK
  - Tests
  - Demo apps (Android, iOS, Windows?)

2) Check that after changes all work as expected.

## Related PRs or issues

[AB#88471](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/88471)

### CODE REVIEW

**Comment by DmitriyKirakosyan** [comment]
What about https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/swagger/ingestion.yaml#L112?

**Review by DmitriyKirakosyan — APPROVED** [review]

**Comment by gn-mloebger** [comment]
Totally agreeing with @CorsairRO .
Why was it removed? What is the alternative?

It would be nice with a little more description in the change log.

**Comment by thisisthekap** [comment]
@AnastasiaKubova Agree as well. Why was this one removed? What is the replacement?

**Comment by DmitriyKirakosyan** [comment]
Hi guys, could you please describe the way you use this API? Custom Properties are not displayed on the App Center Portal and don't affect any existing metrics. It was used in Push service only which was removed quite a while ago.
Do you export analytics data to Application Insight and then query the data based on the exported Custom Properties events?

In case you use custom properties for user identification, there is a dedicated [SetUserId API](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#identify-users).
For other cases I recommend using [Analytics.TrackEvent](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/xamarin#custom-events) with properties.

Please share more information about your API usage if you feel that `SetUserId` and `TrackEvent` is not an alternative for you.

**Comment by gn-mloebger** [comment]
Hi @DmitriyKirakosyan 

> Do you export analytics data to Application Insight and then query the data based on the exported Custom Properties events?
This is exactly the use-case we have. We are using it for data the we do not want/need to show up in the App Center Portal.

Is there an alternative for this?

**Pull request merged**
