### PR TITLE
WPF/WinForms test apps. Send attachments in trackError.

### PR DESCRIPTION
**Pull request by olmisa**
Things to consider before you submit the PR:

* [ ] Has `CHANGELOG.md` been updated?
* [ ] Are tests passing locally?
* [ ] Are the files formatted correctly?
* [ ] Did you add unit tests if this modifies the Windows code?
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?

## Description

Modify the WPF/WinForms test apps to send attachments even when "handle errors" toggle is on. Also ensure that the attachments functionality remains enabled in this case.

## Related PRs or issues

[AB#71076](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/71076)

### CODE REVIEW

**Comment by jaelim-ms** [comment]
This should go to a feature branch.

**Comment by dhei** [comment]
> Retarget this PR on feature/handled-error-attachments (merge code and change in github too).

We created `feature/windows-handled-error-attachments` as feature branch and I retargeted this PR to it.

**Comment by guperrot** [comment]
> > Retarget this PR on feature/handled-error-attachments (merge code and change in github too).
> 
> We created `feature/windows-handled-error-attachments` as feature branch and I retargeted this PR to it.

Need to merge code, doing retarget on GH is not enough to test locally.

**Comment by guperrot** [comment]
> > > Retarget this PR on feature/handled-error-attachments (merge code and change in github too).
> > 
> > 
> > We created `feature/windows-handled-error-attachments` as feature branch and I retargeted this PR to it.
> 
> Need to merge code, doing retarget on GH is not enough to test locally.

Ping

**Comment by olmisa** [comment]
As I understand 'feature/windows-handled-error-attachments' branch contains no API changes and 'feature/handled-error-attachments' should be used for testing. 
Yesterday I have merged 'feature/handled-error-attachments' branch into 'feature/wpf-winforms-trackerror-ui' locally. I have tested changes. As I understand all works in Puppet applications as expected (WPF/WinForms and both DotNetCore versions too).

**Pull request merged**
